package org.schabi.newpipe.error;
public enum UserAction {
    SOMETHING_ELSE, GETTING_MAIN_SCREEN_TAB, REQUESTED_BOOKMARK,
    REQUESTED_STREAM, REQUESTED_CHANNEL, REQUESTED_PLAYLIST,
    REQUESTED_COMMENTS, REQUESTED_FEED, SEARCHED, UI_ERROR,
    SUBSCRIPTION_IMPORT_EXPORT, APP_UPDATE
}
